version: 2.1
orbs:
    codecov: codecov/codecov@3.2.2
    gh: circleci/github-cli@1.0.3
jobs:
  build_shared:
    working_directory: ~/react-auth-shared
    docker:
      - image: cimg/node:14.19.0-browsers
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Tests
          command: |
            yarn test --coverage --watchAll=false
      - run:
          name: Build
          command: |
            yarn build
      - persist_to_workspace:
          root: .
          paths:
            - lib
            - coverage
  coverage_report:
        working_directory: ~/react-auth-shared
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - attach_workspace:
                at: .
            - codecov/upload:
                file: './coverage/clover.xml'
                token: CODECOV_TOKEN

  publish:
    docker:
      - image: cimg/node:14.19.0-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish @brightlayer-ui/react-auth-shared
          command:  |
            yarn publish:package -b $CIRCLE_BRANCH

workflows:
  version: 2
  react_auth_shared:
    jobs:
      - build_shared
      - publish:
          requires:
            - build_shared
          filters:
            branches:
              only:
                - master
                - dev
      - coverage_report:
           requires:
                - build_shared
           filters:
                branches:
                    only:
                        - master
